### ISSUE TITLE
How do set up automatic approvals

### ISSUE THREAD

**Issue by gwinterhalter** [Azure/active-directory-dotnet-graphapi-b2bportal-web#19]
How do set up automatic approvals?

**Comment by bretthackermsft** [comment]
Admin | Manage Domains
![B2BAutoApprove](https://user-images.githubusercontent.com/24515695/54946967-3a1f3580-4f07-11e9-9f57-b40cecb98cfd.png)

**Comment by gwinterhalter** [comment]
Thanks. Is there a way to set auto approve for all organizations without creating the above for each?

**Comment by bretthackermsft** [comment]
There are over 1 billion user accounts worldwide in Azure Active Directory. You would want to let any or all of those place themselves as guests in your corporate tenant?

You may be trying to use the wrong tool for the job. Take a look at B2C. https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-overview

**Comment by markandaymishraepms** [comment]
Hi 

Auto approve is not working even after adding the domain like outlook.com or goepmsolutions.com

I tested with in demo office 365 accounts as well but still request is showing under appeal queue in admin login

**Comment by markandaymishraepms** [comment]
I have one more question. Can we configure email alert to approver on request from external user? 


Kindly share the steps if any way to do so.

Thanks

**Comment by bretthackermsft** [comment]
You can't set auto-approve for any domain that's not already in Azure Active Directory...by design.

![invalidDomain](https://user-images.githubusercontent.com/24515695/55023452-d2322300-4fca-11e9-936e-87f364b0d5b0.png)
![DomainHelp](https://user-images.githubusercontent.com/24515695/55023459-d5c5aa00-4fca-11e9-9aa2-a686091d2d21.png)

Regarding alerts - this is a proof of concept/sample application. It is intended to be used as a starting point for a custom solution. The code is fairly well self-documented, you or a partner should be able to fork it and easily customize it to send a notification.

**Comment by markandaymishraepms** [comment]
Thanks for quick response

But auto approve is no working for outlook.com even its getting verified while adding the same

It is not working for our one of the demo domain as well m365x705422.onmicrosoft.com

**Comment by bretthackermsft** [comment]
Outlook.com is validating as an Azure AD tenant, but it's an MSA and not a work/school tenant. Think this through - if ANYONE with an @outlook.com email address were auto-invited to your tenant, you're not actually validating anything. The point of this auto-approval is that you have an agreement with another entity that's using Azure Active Directory, and you are OK with anyone associated with that company being invited to your tenant. The fact that they have to log in and authenticate to their work tenant assures you that they are associated, and still gainfully employed or otherwise authorized. Outlook.com doesn't fit that description. 

As mentioned above, you may need to be looking at the B2C product if you're looking for consumer account self-registration.

**Comment by bretthackermsft** [comment]
(With regards to your demo tenant, I can't speak to that but I just tested with my own external tenant and a new account and auto-approval worked as it's supposed to.)

**Comment by markandaymishraepms** [comment]
Thanks for your details.

Do we have to configure anything in our azure ad to allow our demo tenant user request auto approve?

I have just added the domain to b2b portal by selling auto approve based on your  screenshot provided earlier?

**Comment by bretthackermsft** [comment]
Provided you have configured your app registrations correctly, you shouldn't have to do anything else.

**Comment by markandaymishraepms** [comment]
Hi

About the alert, what module need to change to send email to admin on new request on self service portal?

**Comment by markandaymishraepms** [comment]
Hi,

we have deployed the GitHub Code to configure the Azure B2B Self Service Portal.
as you have mentioned that this code is dynamic and can be modified as per the requirement. 
 
also, this code offers auto approval by setting the external domain but for us its not working. 
 
We need the following to be added additionally .
 
1.	Update the code to send email alert to admin on each request
2.	Update admin approval page to have option to add the user to particular Group to assign the permission on the selected page
3.	can you provide a Graph REST API to read external users?

Can you please provide the quotation for the above to get this for our configuration. 

Thanks and Regards: 
Markanday Mishra

**Comment by bretthackermsft** [comment]
Sorry, your best bet is to engage with a developer that can fork this and modify it for your needs. There are a number of options - here is a list of Microsoft Solution Providers that you can search: https://www.microsoft.com/en-us/solution-providers/home
